# Generated by Django 2.1 on 2018-08-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='host_user_bind',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
