# Generated by Django 2.1 on 2018-08-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20180828_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='cmd',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session',
        ),
    ]
