# Generated by Django 2.1 on 2018-08-29 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20180829_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='cmd',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='audit.SessionLog'),
            preserve_default=False,
        ),
    ]
