# Generated by Django 2.0.2 on 2018-09-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20180903_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host_user_binds',
        ),
    ]
